# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b619d8b384633280bb72ad2004be8993"
name = "Standhigher Lab"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[app_proxy]
url = "/api/app-proxy"
prefix = "apps"
subpath = "besttrack-page-builder"
