import { createPageDocument, type BlockDefinition, type JsonValue, type PageBuilderExtension, type TemplateDefinition } from "@standhigher/puck-page-builder/runtime";
import { BrandedAnnouncementBlock, BrandedBlogBlock, BrandedOrderItemsBlock, BrandedQueryBlock, BrandedQuickLinksBlock, BrandedRecommendationsBlock, BrandedTextField } from "./branded";

const text = (label: string) => ({ field: "besttrack.branded.text", label });
const brandedBlocks: BlockDefinition[] = [
  { type: "besttrack.branded.announcement", version: 1, label: "Announcement", category: "BestTrack Branded", targets: ["web"], defaultProps: { brandName: "BestTrack Studio", logoUrl: "", message: "Track every order with confidence." }, defaultVariant: "brand", variants: [{ id: "brand", label: "Brand" }, { id: "minimal", label: "Minimal", theme: { "color.primary": "#202223" } }], fields: { brandName: text("Brand name"), logoUrl: text("Logo URL"), message: text("Announcement") }, render: { web: BrandedAnnouncementBlock } },
  { type: "besttrack.branded.query", version: 1, label: "Order query", category: "BestTrack Branded", targets: ["web"], defaultProps: { eyebrow: "ORDER SUPPORT", heading: "Where is my order?", submitLabel: "Find my order", defaultTrackingNumber: "BT-2048-DEMO" }, defaultVariant: "brand", variants: [{ id: "brand", label: "Brand" }, { id: "compact", label: "Compact", theme: { spacing: "12px" } }], fields: { eyebrow: text("Eyebrow"), heading: text("Heading"), submitLabel: text("Button label"), defaultTrackingNumber: text("Default tracking number") }, render: { web: BrandedQueryBlock } },
  { type: "besttrack.branded.order-items", version: 1, label: "Order items", category: "BestTrack Branded", targets: ["web"], defaultProps: { heading: "Your order" }, defaultVariant: "brand", variants: [{ id: "brand", label: "Brand" }, { id: "minimal", label: "Minimal" }], fields: { heading: text("Heading") }, render: { web: BrandedOrderItemsBlock } },
  { type: "besttrack.branded.recommendations", version: 1, label: "Recommended products", category: "BestTrack Branded", targets: ["web"], defaultProps: { heading: "Selected for you" }, defaultVariant: "brand", variants: [{ id: "brand", label: "Brand" }, { id: "editorial", label: "Editorial", theme: { "color.surface": "#fff7ed" } }], fields: { heading: text("Heading") }, render: { web: BrandedRecommendationsBlock } },
  { type: "besttrack.branded.quick-links", version: 1, label: "Quick links", category: "BestTrack Branded", targets: ["web"], defaultProps: { heading: "Need help?", primaryLabel: "Shipping help", primaryHref: "/pages/shipping", secondaryLabel: "Contact us", secondaryHref: "/pages/contact" }, defaultVariant: "brand", variants: [{ id: "brand", label: "Brand" }], fields: { heading: text("Heading"), primaryLabel: text("Primary link label"), primaryHref: text("Primary link URL"), secondaryLabel: text("Secondary link label"), secondaryHref: text("Secondary link URL") }, render: { web: BrandedQuickLinksBlock } },
  { type: "besttrack.branded.blog", version: 1, label: "Blog", category: "BestTrack Branded", targets: ["web"], defaultProps: { heading: "From our journal", articleTitle: "Delivery tips for every season", excerpt: "Simple ways to make every delivery feel considered.", articleHref: "/blogs/news", linkLabel: "Read the story" }, defaultVariant: "brand", variants: [{ id: "brand", label: "Brand" }], fields: { heading: text("Heading"), articleTitle: text("Article title"), excerpt: text("Excerpt"), articleHref: text("Article URL"), linkLabel: text("Link label") }, render: { web: BrandedBlogBlock } }
];

export function createBrandedTemplate(): TemplateDefinition {
  return { id: "besttrack.branded", version: 1, name: "Branded", target: "web", source: "built-in", requiredBlocks: brandedBlocks.map((block) => block.type), theme: { "color.primary": "#7c3aed", "color.background": "#f8f7ff", "color.surface": "#ffffff", "color.text": "#231942", "color.border": "#ddd6fe", "font.family": "Georgia, serif", radius: "18px", spacing: "24px" }, create: () => createPageDocument({ pageId: "besttrack-branded", target: "web", templateId: "besttrack.branded", templateVersion: 1, settings: { locale: "en", seoTitle: "Track your order with BestTrack Studio" }, blocks: brandedBlocks.map((block, index) => ({ id: `branded-${index + 1}`, type: block.type, version: block.version, props: block.defaultProps as Record<string, JsonValue>, variant: block.defaultVariant, style: {} })) }) };
}

export const bestTrackBrandedExtension: PageBuilderExtension = Object.freeze({ name: "besttrack.branded", version: "0.7.1", fields: [{ type: "besttrack.branded.text", component: BrandedTextField }], blocks: brandedBlocks, templates: [createBrandedTemplate()] });
