import { createPageDocument, type BlockDefinition, type JsonValue, type PageBuilderExtension, type TemplateDefinition } from "@standhigher/puck-page-builder/runtime";
import { ReadyToGoDeliveryBlock, ReadyToGoProgressBlock, ReadyToGoQueryBlock, ReadyToGoRecommendationsBlock, ReadyToGoTextField } from "./ready-to-go";

const readyToGoBlocks: BlockDefinition[] = [
  { type: "besttrack.ready-to-go.query", version: 1, label: "Order query", category: "BestTrack Ready-to-go", targets: ["web"], defaultProps: { heading: "Track your order", submitLabel: "Track package", defaultTrackingNumber: "BT-2048-DEMO" }, defaultVariant: "default", variants: [{ id: "default", label: "Default" }], fields: { heading: { field: "besttrack.ready-to-go.text", label: "Heading" }, submitLabel: { field: "besttrack.ready-to-go.text", label: "Button label" }, defaultTrackingNumber: { field: "besttrack.ready-to-go.text", label: "Default tracking number" } }, render: { web: ReadyToGoQueryBlock } },
  { type: "besttrack.ready-to-go.progress", version: 1, label: "Shipment progress", category: "BestTrack Ready-to-go", targets: ["web"], defaultProps: { heading: "Shipment progress" }, defaultVariant: "default", variants: [{ id: "default", label: "Default" }], fields: { heading: { field: "besttrack.ready-to-go.text", label: "Heading" } }, render: { web: ReadyToGoProgressBlock } },
  { type: "besttrack.ready-to-go.delivery", version: 1, label: "Delivery information", category: "BestTrack Ready-to-go", targets: ["web"], defaultProps: { heading: "Delivery information" }, defaultVariant: "default", variants: [{ id: "default", label: "Default" }], fields: { heading: { field: "besttrack.ready-to-go.text", label: "Heading" } }, render: { web: ReadyToGoDeliveryBlock } },
  { type: "besttrack.ready-to-go.recommendations", version: 1, label: "Recommended products", category: "BestTrack Ready-to-go", targets: ["web"], defaultProps: { heading: "You may also like" }, defaultVariant: "default", variants: [{ id: "default", label: "Default" }], fields: { heading: { field: "besttrack.ready-to-go.text", label: "Heading" } }, render: { web: ReadyToGoRecommendationsBlock } }
];

export function createReadyToGoTemplate(): TemplateDefinition {
  return { id: "besttrack.ready-to-go", version: 1, name: "Ready-to-go", target: "web", source: "built-in", requiredBlocks: readyToGoBlocks.map((block) => block.type), theme: { "color.primary": "#005bd3", "color.background": "#f6f6f7", radius: "12px", spacing: "20px" }, create: () => createPageDocument({ pageId: "besttrack-ready-to-go", target: "web", templateId: "besttrack.ready-to-go", templateVersion: 1, settings: { locale: "en", seoTitle: "Track your order" }, blocks: readyToGoBlocks.map((block, index) => ({ id: `ready-to-go-${index + 1}`, type: block.type, version: block.version, props: block.defaultProps as Record<string, JsonValue>, variant: block.defaultVariant, style: {} })) }) };
}

export const bestTrackPageExtension: PageBuilderExtension = Object.freeze({ name: "besttrack.ready-to-go", version: "0.7.0", fields: [{ type: "besttrack.ready-to-go.text", component: ReadyToGoTextField }], blocks: readyToGoBlocks, templates: [createReadyToGoTemplate()] });
